= Назначение и функции модуля

_{wf}_ является _базовым модулем_ системы {dv}, который реализует функции СУБП и предоставляет инструментарий для настройки БП.

Модуль предназначен для формального описания и автоматизации бизнес-процессов, типичных для документооборота организации.

.Модуль обеспечивает выполнение следующих функциональных задач:
* Создание шаблонов БП в виде графической схемы с помощью "Конструктора бизнес-процессов".
* Исполнение и мониторинг за исполнением БП.
* Создание скриптов (сценариев) БП на языках C# и Visual Basic .Net в интегрированной среде разработки.
* Получение данных из внешних (по отношению к модулю) программ и системы {dv}.

Модуль поддерживает возможность кластеризации, при которой несколько экземпляров модуля объединяются для распределенной обработки БП из общей очереди БП.

Модуль поддерживает одновременную работу с несколькими базами данных (мультитенантный режим). Подробнее о настройке модуля в мультитенантном режиме в пункте xref:admin:console.adoc[Настройки модуля в Консоли настройки {dv}].