= Назначение и функции модуля

_{wf}_ является _базовым модулем_ системы {dv}, который реализует функции СУБП и предоставляет инструментарий для настройки БП.

модуль предназначен для формального описания и автоматизации бизнес-процессов, типичных для документооборота организации.

.модуль обеспечивает выполнение следующих функциональных задач:
* создание шаблонов БП в виде графической схемы с помощью "Конструктора бизнес-процессов";
* исполнение и мониторинг за исполнением БП;
* создание скриптов (сценариев) БП на языках C# и Visual Basic .Net в интегрированной среде разработки;
* получение данных из внешних (по отношению к модулю) программ и системы {dv}.

модуль поддерживает возможность кластеризации, при которой несколько экземпляров модуля объединяются для распределенной обработки БП из общей очереди БП.

модуль поддерживает одновременную работу с несколькими базами данных (мультитенантный режим). Подробнее о настройке модуля в мультитенантном режиме в пункте xref:admin:wf-console.adoc[Настройки модуля в Консоли настройки {dv}].