= Аннотация

[#general]
== Область применения

Настоящий раздел документации описывает работу с модулем _{wf}_. Данный раздел документации предназначен для администраторов и инженеров {dv}.

Модуль _{wf}_ добавляет в систему {dv} функциональность системы управления бизнес-процессами и инструментарий для настройки БП.

Модуль {wf} предназначен для формального описания и автоматизации бизнес-процессов, типичных для документооборота организации.

.Модуль обеспечивает выполнение следующих функциональных задач:
* Создание шаблонов БП в виде графической схемы с помощью _Конструктора бизнес-процессов_.
* Исполнение и мониторинг за исполнением БП.
* Создание скриптов (сценариев) БП на языках "C#" и "Visual Basic .Net" в интегрированной среде разработки.
* Получение данных из внешних (по отношению к модулю) программ и системы {dv}.

Модуль поддерживает возможность кластеризации, при которой несколько экземпляров модуля объединяются для распределенной обработки БП из общей очереди БП.

[#structure]
== Как организована документация

.Документация модуля содержит следующие разделы:
* xref:module-structure.adoc[Структура модуля] -- перечислены составные части модуля.
* Администрирование модуля:
* Приведены общие сведения о модуле, требования к подготовке пользователей, описание основных сущностей модуля.
* xref:workflow-service.adoc[Описание] сервиса Workflow.
** Инструкция по установке xref:admin:install.adoc#server[серверной] и xref:admin:install.adoc#client[клиентской] частей модуля.
** Функции администратора {dv}.
** Примеры настройки бизнес-процессов.
** Инструкция по разработке бизнес-процессов, описание шлюзов и функций БП.
** <<general,Общие сведения о модуле>> -- общие сведения о модуле, требования модуля к программному и аппаратному обеспечению компьютера.
** xref:admin:install.adoc[Инструкция] -- по установке и настройке модуля.
** xref:admin:update-module.adoc[Инструкция] по обновлению модуля.
** Администрирование модуля -- описание настроек модуля, выполняемых администратором {dv}.
* Руководство пользователя:
** xref:user:launch.adoc[Подготовка к работе] (приведены условия для настройки бизнес-процессов в программе {wincl}/РМА).
** xref:user:bp-designer.adoc[Конструктор бизнес-процессов] -- описание основного инструмента разработки бизнес-процессов.
** Настройка бизнес-процессов -- приведена инструкция по настройке бизнес-процессов.
** xref:user:Variable_Types.adoc[Типы переменных] -- приведен перечень типов переменных бизнес-процессов.
** xref:user:FunctionDefinition.adoc[Описание функций бизнес-процессов] -- приведено описание функция для конструирования бизнес-процессов.
