= Функции шлюза к почтовой системе

Шлюз к почтовой системе позволяет проводить мониторинг входящих сообщений и обмен данными с почтовыми ящиками пользователя, а также отправлять почтовые сообщения. Работа осуществляется согласно настройкам шлюза в текущем процессе, карточке _Системные настройки_ (ветка _Шлюзы_) или в _Консоли Настройки {dv}_.

По умолчанию в свойствах бизнес-процесса установлены параметры сервера, указанные в _Консоли Настройки {dv}_. Эти настройки можно изменить так, чтобы бизнес-процесс осуществлял работу с любым другим ящиком электронной почты.

.Чтобы изменить настройки:
. Нажмите на панели инструментов шаблона бизнес-процесса кнопку *Настройки*.
. В открывшемся диалоговом окне _Свойства процесса_ перейдите на вкладку _Шлюзы_.
 . Выберите из списка шлюзов *_Шлюз к почте_* и нажмите кнопку *Изменить*.
. В появившемся диалоговом окне свойств шлюза перейдите на вкладку _Шлюз к почте_.
. Снимите флаг `*Использовать настройки по умолчанию*` и установите новые параметры соединения:
+
* _Тип сервера_.
* _Имя профиля_, который должен быть создан заранее.
* _E-mail сервера_.

После выполнения указанных действий бизнес-процесс будет производить мониторинг почтового ящика в соответствии с указанными пользователем параметрами.

.Шлюз к почтовой системе работает со следующими типами переменных:
* _Почтовое сообщение_: тип переменной, предназначенный для работы с сообщениями электронной почты. +
Переменная данного типа не имеет явно заданного значения, оно присваивается с помощью функции _Мониторинг сообщений_.
+
* _Почтовое вложение_: тип переменной, предназначенный для работы с вложениями (attachment), прикрепленными к сообщениям электронной почты.
* _Почтовый адресат_: тип переменной, предназначенный для работы с пользователями, указанными получателями сообщений.

Бизнес-процесс может работать как в 32- так и в 64-разрядном режиме со всеми типами почтовых серверов, кроме Microsoft Exchange, при работе с которым бизнес-процесс всегда исполняется в 32-разрядном режиме.

[WARNING]
====
Взаимодействие функции БП через почтовый шлюз с почтовым ящиком, содержащим большое количество сообщений, ведет к увеличению времени выполнения всего бизнес-процесса.

Исполнение других бизнес-процессов на это время приостанавливается. Необходимо избегать обращений функций к переполненным почтовым ящикам и своевременно очищать подключенные ящики.

Рекомендуется выделять для конкретных БП отдельные почтовые ящики с автоматической очисткой (например, удалять обработанные письма самим БП).
====
