= Функции шлюза к {dv}

Шлюз к {dv} предназначен для обработки приложением _{wf}_ объектов {dv}.

По умолчанию в свойствах бизнес-процесса установлены параметры того же сервера, на котором работает приложение. Параметры можно изменить таким образом, чтобы задействовать другой сервер {dv}.

Для этого откройте диалоговое окно _Свойства процесса_ нажатием кнопки *Настройки*, перейти на вкладку _Шлюзы_ и дважды нажмите на опцию _Шлюз к {dv}_. В открывшемся диалоговом окне перейдите на вкладку _Настройки соединения_ и, сняв флаг `*Использовать настройки по умолчанию*`, укажите параметры другого сервера, на котором установлена система {dv}:

* _Адрес сервера_ {dv}, c которым будет работать бизнес-процесс.
* _Имя базы данных_, с которой будет работать бизнес-процесс.
* _Начальный URL_ сервера {dv}, который будет использоваться в шлюзе для создания URL на карточки и папки. Обычно задан как `\http://server/{dv}`.

.Возможности шлюза по обработке объектов {dv} включают:
* Поиск по определенным критериям имеющихся карточек и обнаружение вновь создаваемых.
* Создание ярлыков карточек в указанных папках.
* Автоматическое формирование бизнес-процессов по организации согласования документов и исполнения задач, а также описание заданий, которые могут потребоваться при выполнении бизнес-процесса с возможностью их модификации в зависимости от обстоятельств.

Далее приводится список типов переменных, которыми оперируют функции шлюза с {dv}, с указанием значений, которые эти переменные могут принимать:

Карточка DV::
Ссылка на карточку {dv}.

Ярлык DV::
Ссылка на ярлык {dv}.

Папка DV::
Ссылка на папку {dv}.

Файл DV::
Ссылка на карточку файла {dv}.

Секция карточки DV::
Ссылка на секцию карточки {dv}.

Строка секции карточки DV::
Ссылка на строку секции карточки {dv}.

Роль DV::
Ссылка на роль из справочника сотрудников {dv}.

Сотрудник DV::
Ссылка на сотрудника из справочника сотрудников {dv}.

Подразделение DV::
Ссылка на организацию (или подразделение организации) из справочника сотрудников {dv}.

Группа DV::
Ссылка на группу из справочника сотрудников {dv}.

Значение переменной процесса DV::
Ссылка на значение переменной бизнес-процесса.

Переменная процесса DV::
Ссылка на переменную бизнес-процесса.

Перечисление DV::
Ссылка на поле типа `Enum` из карточки {dv}.

Процесс DV::
Ссылка на бизнес-процесс.

Тип карточки DV::
Ссылка на тип карточки {dv}.

При обмене данными между бизнес-процессом и карточкой файла, указанной в поле _Карточка_, переменная бизнес-процесса, в которую возвращается значение поля карточки файла _Тип версий_, должна иметь строковый тип. Возможные возвращаемые значения соответствуют указанному в карточке файла типу создания версий на английском языке (ручной -- `Manual`, автоматический -- `Auto`, нет -- `None`).
