=  Разрешение перенаправления при автообнаружении конечной точки Exchange Web Services

При подключении почтового шлюза Workflow к серверу Exchange Web Services используется функция автообнаружения конечной точки EWS (https://docs.microsoft.com/ru-ru/exchange/client-developer/exchange-web-services/autodiscover-for-exchange).

По умолчанию, если сервер автообнаружения EWS возвращает статус, перенаправляющий шлюз к почте Workflow на другой адрес подключения, автообнаружение будет завершено с ошибкой. Чтобы разрешить такие перенаправления, добавьте в реестр ОС с установленным сервером Workflow специальный параметр:

* ветка: [.ph .filepath]`HKLM\SOFTWARE\DocsVision\Workflow\5.5\WorkflowServer`
* название параметра: WebAllowRedirect;
* тип: DWORD;
* значение: 1.

Перезапустите службу Workflow.

Если в организации используется кластер Workflow, настройку нужно выполнить на всех узлах.

[NOTE]
====
[.note__title]#Note:# Обратите внимание, ветка [.ph .filepath]`HKLM\SOFTWARE\DocsVision\Workflow\5.5\WorkflowServer` — это ветка, в которой хранятся настройки по умолчанию. В версиях модуля с поддержкой мультитенантности (5.5.3 и выше) настройки для каждой БД настройки хранятся в собственной ветке реестра.
====

Функция автообнаружения EWS может быть отключена, если указать прямой адрес EWS. Когда при настройке мониторинга почты в поле _Адрес сервера для подключения_ указана почта, функция автообнаружения конечной точки EWS будет работать как раньше. Когда в поле указан явный адрес, автообнаружение будет отключено и будет использован указанный адрес.

*Parent topic:* xref:Process_Management_Mail_Settings.adoc[Настройка почты]
