=  Авторизация через OAuth при использовании Exchange Web Services

Microsoft прекратила поддержку обычной проверки подлинности в Exchange Online. В связи с этим была добавлена возможность авторизации через OAuth при использовании Exchange Web Services.

[NOTE]
====
[.note__title]#Прим.:# Индивидуальная настройка шлюза на уровне UI БП при этом не поддерживается.
====

Чтобы использовать OAuth с EWS необходимо:

. [.ph .cmd]#Настроить приложение в требуемом тенанте Azure AD согласно https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-authenticate-an-ews-application-by-using-oauth[инструкции]. Когда есть варианты "delegated authentication" или "app-only authentication", нужно выбирать вариант "app-only authentication". В процессе настройки, необходимо сохранить три значения: #
+
* Идентификатор созданного приложения (идентификатор клиента, в настройках приложения).
* Идентификатор каталога (идентификатор тенанта, в настройках приложения).
* Клиентский секрет (из раздела "Сертификаты и секреты").
. [.ph .cmd]#В реестре, в ветке настроек Worfklow ([.ph .filepath]`HKEY_LOCAL_MACHINE\SOFTWARE\DocsVision\Workflow\5.5\WorkflowServer\Tenants`) у подчинённой ветки с именем нужной БД задать следующие настройки:#
+
* `WebUseOAuth (DWORD)`: 1.
* `WebOauthClientId (строка)`: идентификатор созданного приложения.
* `WebOauthTenantId (строка)`: идентификатор каталога (идентификатор тенанта).
* `WebOauthExtData (строка)`: клиентский секрет.
. [.ph .cmd]#В консоли настроек Docsvision, в разделе "Управление процессами" включить использование Exchange Web Services с использованием актуального адреса электронной почты, соответствующего нужному почтовому ящику.#

[[oauth__postreq_gd3_sbl_1vb]]
При использовании OAuth, в настройке [.dfn .term]_Адрес сервера для подключения_ (аналогично настройке `WebAutodiscoverURL` в реестре) должен быть указан адрес email. Использование прямого адреса для подключения в этом случае не допускается.

*На уровень выше:* xref:Process_Management_Mail_Settings.adoc[Настройка почты]
