=  Требования отдельной установки СУБП

Данные требования предъявляются серверной частью модуля «Управление процессами» для установки отдельно от сервера Docsvision.

== Аппаратные требования

* *Процессор*: 2 ГГц или выше, 8 ядер;
* *Оперативная память*: от 8 ГБ;
* *Система хранения данных*: от 250 ГБ (рекомендуется твердотельный накопитель);

== Программные требования

* *Операционная система*
** Microsoft Windows Server 2019 (Standard, DataCenter);
** Microsoft Windows Server 2016 ( Standard, DataCenter);
** Microsoft Windows Server 2012 R2 (Standard, DataCenter);
** Microsoft Windows Server 2012 (Standard, DataCenter);
** Microsoft Windows 10 (Pro, Enterprise);
** Microsoft Windows 8/8.1 (Pro, Enterprise).
* *Обязательное программное обеспечение*
. Microsoft .NET Framework 4.6.1.
* *Модули Docsvision*
. Серверная часть модуля «Docsvision 5. Платформа» версии 5.5.2 сборка 4279 и выше: установить компоненты «Сервер приложений» и «Набор клиентских компонентов сервера», настраивать новый экземпляр сервера Docsvision не нужно.
. Серверная часть модуля «Docsvision 5. Базовые объекты» версии 5.5.3 сборка 4237 и выше.
. Серверная часть приложения «Docsvision 5. Управление документами» версии 5.5.3 сборка 4246 и выше.
. Серверная часть модуля «Docsvision 5. Конструктор согласований» версии 5.5.2 сборка 4174 и выше.
. Серверная часть приложения «Docsvision 5. Делопроизводство 4.5» версии 5.5.2 сборка 4173 и выше.
. Серверная часть модуля «Docsvision 5. Windows-клиент» версии 5.5.2 сборка 4191 и выше.

*Parent topic:* xref:Required_resources.adoc[Необходимые ресурсы]
