=  Необходимое программное обеспечение

== Требования серверной части Модуля

. [#concept_vgh_3qm_2db__OSs]#*Операционная система*#
* Microsoft Windows Server 2019 (Standard, DataCenter);
* Microsoft Windows Server 2016 ( Standard, DataCenter);
* Microsoft Windows Server 2012 R2 (Standard, DataCenter);
* Microsoft Windows Server 2012 (Standard, DataCenter);
* Microsoft Windows 10 (Pro, Enterprise);
* Microsoft Windows 8/8.1 (Pro, Enterprise).
. [#concept_vgh_3qm_2db__POs]#*Обязательное программное обеспечение*#
[loweralpha]
.. Microsoft .NET Framework 4.6.1.
. Дополнительное программное обеспечение:
[loweralpha]
.. Microsoft Outlook (только x86) – для настройки учетной записи Microsoft Exchange (для использования шлюза к почте в БП). Если отправлять/получать электронные письма через Microsoft Exchange в БП не планируется, данное ПО не требуется.
. *Модули Docsvision*:
[loweralpha]
.. Серверная часть модуля «Docsvision 5. Платформа» версии 5.5.2 сборка 4553 и выше.
.. Серверная часть модуля «Docsvision 5. Базовые объекты» версии 5.5.3 сборка 5367 и выше.
.. Серверная часть приложения «Docsvision 5. Управление документами» версии 5.5.3 сборка 5316 и выше.
.. Серверная часть модуля «Docsvision 5. Конструктор согласований» версии 5.5.2 сборка 4221 и выше.
.. Серверная часть приложения «Docsvision 5. Делопроизводство 4.5» версии 5.5.2 сборка 4203 и выше.
.. Серверная часть модуля «Docsvision 5. Windows-клиент» версии 5.5.2 сборка 4248 и выше.

== Требования клиентской части Модуля

. *Модули Docsvision*:
[loweralpha]
.. Клиентская часть модуля «Docsvision 5. Платформа» версии 5.5.2 сборка 4553 и выше.
.. Клиентская часть модуля «Docsvision 5. Базовые объекты» версии 5.5.3 сборка 5367 и выше.
.. Клиентская часть приложения «Docsvision 5. Управление документами» версии 5.5.3 сборка 5316 и выше.
.. Клиентская часть модуля «Docsvision 5. Конструктор согласований» версии 5.5.2 сборка 4221 и выше.
.. Клиентская часть приложения «Docsvision 5. Делопроизводство 4.5» версии 5.5.2 сборка 4203 и выше.
.. Клиентская часть модуля «Docsvision 5. Windows-клиент» версии 5.5.2 сборка 4248 и выше.

*На уровень выше:* xref:Required_resources.adoc[Необходимые ресурсы]
