= Просмотр журнала бизнес-процесса

Для отладки, обнаружения ошибок и мест сбоев может оказаться полезным поэтапный просмотр выполнения экземпляра бизнес-процесса, который фиксируется в журнале бизнес-процесса. Журнал открывается при нажатии кнопки *Журнал процесса* на панели инструментов карточки активного или завершенного экземпляра бизнес-процесса.

Кроме того, возможен просмотр журнала активного бизнес-процесса в целях уточнения хода его выполнения; при этом получение последних данных о ходе бизнес-процесса можно получить при помощи кнопки *Обновить*.

Информация о выполнении представлена в виде таблицы, содержащей следующие колонки:

Тип::
  Информация о выполнении или ошибка выполнения.
Порядок::
  Номер сообщения по порядку.
Дата::
  Дата и время происходящего события.
Приоритет::
Сообщение::
  Описание выполняемого действия.
Имя функции::
  Имя функции, выполняющей действие.
Состояние::
  Выполнено или завершается по ошибке.

В случае если записи журнала не помещаются на экране, можно изменить высоту строк или ширину столбцов журнала. Для этого следует поместить курсор на левую (для изменения ширины столбца -- верхнюю) границу таблицы и, когда он изменит форму (на горизонтальной линии курсор принимает форму стрелки вверх–вниз, на вертикальной -- стрелки вправо-влево), щелкнуть кнопкой мыши и, не отпуская ее, изменить высоту строки до желаемого размера.

Еще более детальные сведения о выполнении бизнес-процесса можно получить, нажав кнопку *Подробнее* или дважды щелкнув по одной из строк журнала. Поля открывающегося при этом окна [.keyword .wintitle]*Данные сообщения* содержат следующие сведения о ходе бизнес-процесса:

Дата::
  Дата и время события.
Тип::
  Информация о выполнении или ошибка выполнения.
Функция::
  Название выполняемой функции.
Приоритет::
Состояние функции::
Сообщение::
  Описание выполняемое действие.

Для дальнейшей детализации данных журнала следует нажать кнопку *Больше*, открывающую в окне дополнительные поля *Детали сообщения*, *Входящие данные* и *Исходящие данные*.

Навигация по сообщениям о ходе выполнения бизнес-процесса осуществляется при помощи кнопок *Предыдущее* и *Следующее*. Уменьшить окно, свернув дополнительные поля, можно при помощи кнопки *Меньше*.

Кнопка *Удалить* позволяет удалить сообщение из журнала.

Экспортировать содержимое журнала бизнес-процесса в файл формата [.keyword .parmname]_.xml_ можно нажав кнопку *Экспорт*.
