= Просмотр журнала изменений значения переменной

Помимо просмотра хода выполнения бизнес-процесса, можно проследить последовательность изменения значений переменной при помощи специального журнала. Эта функция также может оказаться полезной для обнаружения ошибок и мест сбоев бизнес-процесса. Журнал ведется в том случае, если при определении параметров переменной был установлен флаг *Сохранять историю значений при исполнении бизнес-процесса*.

Просмотр журнала доступен как для завершенных, так и для активных экземпляров бизнес-процессов.

Для открытия журнала изменений значения переменной откройте окно *Свойства процесса* при помощи кнопки панели инструментов *Настройки*. Перейдите на вкладку *Переменные* и выделите переменную в списке. Нажмите кнопку *Изменить* или дважды щелкните по нужной переменной и в открывшемся окне нажмите кнопку *Журнал*.

В открывшемся окне *Журнал значений* переменной перечислены дата и время изменения значения выбранной переменной, а также присваиваемые ей в эти моменты значения.

Кнопка *Обновить* позволяет уточнить сведения с учетом изменений, происшедших с момента открытия журнала.
