= Сервис для работы с карточкой документа

[width="100%",cols="33%,41%,26%",options="header",]
|===
|Функция |Параметры функции |Тип значения параметра
|Блокировка основного файла a|
Документ

Файл

Путь к файлу

a|
Карточка DV

Строка секции карточки DV

Строка

|Блокировка основного файла с сохранением во временную директорию a|
Документ

Файл

Возвращаемое значение

a|
Карточка DV

Строка секции карточки DV

Строка, выходной параметр

|Добавление дополнительного файла a|
Документ

Путь к файлу

Возвращаемое значение

a|
Карточка DV

Строка

Строка секции карточки DV, выходной параметр

|Добавление дополнительного файла по версионному файлу a|
Документ

Карточка файла с версиями

Возвращаемое значение

a|
Карточка DV

Файл DV

Строка секции карточки DV, выходной параметр

|Добавление дополнительных файлов a|
Документ

Пути к файлам

Возвращаемое значение

a|
Карточка DV

Строка, коллекция

Строка секции карточки DV, выходной параметр, коллекция

|Добавление комментария к основному файлу a|
Документ

Файл

Комментарий

Возвращаемое значение

a|
Карточка DV

Строка секции карточки DV

Строка

Да/Нет, выходной параметр

|Добавление основного файла a|
Документ

Путь к файлу

Возвращаемое значение

a|
Карточка DV

Строка

Строка секции карточки DV, выходной параметр

|Добавление основных файлов a|
Документ

Пути к файлам

Возвращаемое значение

a|
Карточка DV

Строка, коллекция

Строка секции карточки DV, выходной параметр, коллекция

|Загрузка новой версии основного файла документа a|
Документ

Файл

Путь к файлу

Сотрудник

a|
Карточка DV

Строка секции карточки DV

Строка

Сотрудник DV

|Отмена блокировки основного файла a|
Документ

Файл

a|
Карточка DV

Строка секции карточки DV

|Переименовать дополнительный файл a|
Документ

Файл

Значение

a|
Карточка DV

Строка секции карточки DV

Новое название файла

|Переименовать основной файл a|
Документ

Файл

Значение

a|
Карточка DV

Строка секции карточки DV

Новое название файла

|Получить все файлы документа a|
Документ

Возвращаемое значение

a|
Карточка DV

Строка секции карточки DV, выходной параметр, коллекция

|Получить дополнительные файлы a|
Документ

Возвращаемое значение

a|
Карточка DV

Строка секции карточки DV, выходной параметр, коллекция

|Получить карточку файла с версиями из дополнительного файла a|
Документ

Возвращаемое значение

a|
Строка секции карточки DV

Файл DV, выходной параметр

|Получить карточку файла с версиями из дополнительного файла a|
Документ

Возвращаемое значение

a|
Строка секции карточки DV

Файл DV, выходной параметр

|Получить карточку файла с версиями из файла документа a|
Файл

Возвращаемое значение

a|
Строка секции карточки DV

Файл DV, выходной параметр

|Получить основные файлы a|
Документ

Возвращаемое значение

a|
Карточка DV

Строка секции карточки, выходной параметр, коллекция

|Применить настройки из справочника видов a|
Документ

Вид

a|
Карточка DV

Строка секции карточки DV

|Проверка блокировки основного файла документа a|
Файл

Возвращаемое значение

a|
Строка секции карточки DV

Да/Нет, выходной параметр

|Проверка возможности блокировки основного файла документа a|
Документ

Файл

Принудительно разблокировать

Возвращаемое значение

a|
Карточка DV

Строка секции карточки DV

Да/Нет

Да/Нет, выходной параметр

|Проверка возможности добавления основного файла a|
Документ

Карточка файла с версиями

Возвращаемое значение

a|
Карточка DV

Файл DV

Да/Нет, выходной параметр

|Проверка возможности разблокировки основного файла без сохранения изменений a|
Файл

Возвращаемое значение

a|
Строка секции карточки DV

Да/Нет, выходной параметр

|Проверка возможности разблокировки основного файла с сохранением изменений a|
Документ

Файл

Возвращаемое значение

a|
Карточка DV

Строка секции карточки DV

Да/Нет, выходной параметр

|Проверка возможности редактирования основного файла a|
Документ

Файл

Принудительно разблокировать

Возвращаемое значение

a|
Карточка DV

Срока секции карточки DV

Да/Нет

Да/Нет, выходной параметр

|Проверка возможности удаления основного файла a|
Документ

Файл

Возвращаемое значение

a|
Карточка DV

Строка секции карточки DV

Да/Нет, выходной параметр

|Проверка возможности удаления основных файлов a|
Документ

Файлы

Возвращаемое значение

a|
Карточка DV

Строка секции карточки DV, коллекция

Да/Нет, выходной параметр

|Проверка наличия подписи у основного файла a|
Документ

Файл

Возвращаемое значение

a|
Карточка DV

Строка секции карточки DV

Да/Нет, выходной параметр

|Проверка наличия подписи у основных файлов a|
Документ

Подпись

Возвращаемое значение

a|
Карточка DV

Строка секции карточки DV

Да/Нет, выходной параметр

|Редактирование основного файла a|
Документ

Файл

Путь к файлу

a|
Карточка DV

Строка секции карточки DV

Строка

|Свободен ли основной файл a|
Файл

Возвращаемое значение

a|
Строка секции карточки DV

Да/Нет, выходной параметр

|Свободны ли основные файлы a|
Файлы

Возвращаемое значение

a|
Строка секции карточки DV, коллекция

Да/Нет, выходной параметр

|Снятие блокировки с основного файла с сохранением изменений a|
Документ

Файл

Возвращаемое значение

a|
Карточка DV

Строка секции карточки DV

Да/Нет, выходной параметр

|Снятие блокировки с основного файла с сохранением изменений с добавлением новой версии a|
Документ

Файл

Уровень

Комментарий

Указывает добавлять комментарий к версии файла или файлу

Возвращаемое значение

a|
Карточка DV

Строка секции карточки DV

Целое

Строка

Да/Нет

Да/Нет, выходной параметр

|Снятие блокировки с основного файла с сохранением изменений a|
Документ

Файл

Уровень

Комментарий

Указывает добавлять комментарий к версии файла или файлу

Путь к файлу

Возвращаемое значение

a|
Карточка DV

Строка секции карточки DV

Целое

Строка

Да/Нет

Строка

Да/Нет, выходной параметр

|Снятие блокировки с основного файла с сохранением изменений по пути к файлу a|
Документ

Файл

Путь к файлу

Возвращаемое значение

a|
Карточка DV

Строка секции карточки DV

Строка

Да/Нет, выходной параметр

|Снятие блокировки с основного файла с сохранением изменений по пути к файлу с созданием новой версии a|
Документ

Файл

Уровень

Комментарий

Указывает добавлять комментарий к версии файла или файлу

Путь к файлу

Возвращаемое значение

a|
Карточка DV

Строка секции карточки DV

Целое

Строка

Да/Нет

Строка

Да/Нет, выходной параметр

|Создание карточки документа a|
Путь к файлу

Возвращаемое значение

a|
Строка

Карточка DV, выходной параметр

|Создание карточки документа определенного вида a|
Путь к файлу

Вид

Возвращаемое значение

a|
Строка

Строка секции карточки DV

Карточка DV, выходной параметр

|Сохранение дополнительного файла на диск a|
Документ

Файл

Путь к файлу

a|
Карточка DV

Строка секции карточки DV

Строка

|Сохранение дополнительного файла на диск по пути a|
Документ

Файл

Возвращаемое значение

a|
Карточка DV

Строка секции карточки DV

Строка, выходной параметр

|Сохранение основного файла на диск a|
Документ

Файл

Возвращаемое значение

a|
Карточка DV

Строка секции карточки DV

Строка, выходной параметр

|Сохранение основного файла на диск по пути a|
Документ

Файл

Путь к файлуlink:fntarg_1[^1^]

a|
Карточка DV

Строка секции карточки DV

Строка

|Удаление дополнительного файла a|
Документ

Файл

a|
Карточка DV

Строка секции карточки DV

|Удаление основного файла a|
Документ

Файл

a|
Карточка DV

Строка секции карточки DV

|Экспорт документа в adoc a|
Документ

Возвращаемое значение

a|
Карточка DV

Строка, выходной параметр

|Экспорт документа в adoc файл a|
Документ

Возвращаемое значение

a|
Карточка DV

Строка, выходной параметр

|===

Значение переменной `Файл` с типом _Строка секции карточки DV_ может быть получено с помощью функции _Универсальный обмен данными_ в два шага:

. Секция карточки, содержащая ссылку на Файл, записывается в переменную процесса типа Секция карточки DV
. Строки из подготовленной переменной сохраняются в переменную процесса с типом Строка секции карточки DV/Документ: Файлы.

link:fnsrc_1[^1^] Путь должен содержать имя файла (например, C:\Test\ServerLog.txt).
