=  Функции шлюза к почтовой системе

Шлюз к почтовой системе позволяет проводить мониторинг входящих сообщений и обмен данными с почтовыми ящиками пользователя, а также отправлять почтовые сообщения. Работа осуществляется согласно настройкам шлюза в текущем процессе, карточке [.dfn .term]_Системные настройки_ (ветка [.keyword .parmname]_Шлюзы_) или в [.dfn .term]_Консоли Настройки Docsvision_.

По умолчанию в свойствах бизнес-процесса установлены параметры сервера, указанные в [.dfn .term]_Консоли Настройки Docsvision_, однако эти настройки можно изменить так, чтобы бизнес-процесс осуществлял работу с любым другим ящиком электронной почты. Для этого нажмите на панели инструментов шаблона бизнес-процесса кнопку [.ph .uicontrol]*Настройки*, в открывшемся диалоговом окне [.keyword .wintitle]*Свойства процесса* перейдите на вкладку [.keyword]*Шлюзы*, выберите из списка шлюзов [.kbd .ph .userinput]`Шлюз к почте` и нажмите кнопку [.ph .uicontrol]*Изменить*. В появившемся диалоговом окне свойств шлюза следует перейти на вкладку [.keyword]*Шлюз к почте*, снять флаг [.ph .uicontrol]*Использовать настройки по умолчанию* и установить новые параметры соединения:

* [.keyword]*Тип сервера*;
* [.keyword]*Имя профиля*, который должен быть создан заранее;
* [.keyword]*E-mail сервера*.

После выполнения указанных действий бизнес-процесс будет производить мониторинг почтового ящика в соответствии с указанными пользователем параметрами. Шлюз к почтовой системе работает со следующими типами переменных:

* [.dfn .term]_Почтовое сообщение_: тип переменной, предназначенный для работы с сообщениями электронной почты; переменная данного типа не имеет явно заданного значения, оно присваивается с помощью функции [.keyword]*Мониторинг сообщений*.
* [.dfn .term]_Почтовое вложение_: тип переменной, предназначенный для работы с вложениями (attachment), прикрепленными к сообщениям электронной почты.
* [.dfn .term]_Почтовый адресат_: тип переменной, предназначенный для работы с пользователями, указанными получателями сообщений.

Бизнес-процесс может работать как в 32- так и в 64-разрядном режиме со всеми типами почтовых серверов, кроме Microsoft Exchange, при работе с которым бизнес-процесс всегда исполняется в 32-разрядном режиме.

[NOTE]
====
[.note__title]#Важное замечание:# Взаимодействие (через почтовый шлюз) функции БП с почтовым ящиком, содержащим большое количество сообщений, ведет к увеличению времени выполнения всего бизнес-процесса. Исполнение других бизнес-процессов на это время приостанавливается. Необходимо избегать обращений функций к переполненным почтовым ящикам и своевременно очищать подключенные ящики. Рекомендуется выделять для конкретных БП отдельные почтовые ящики с автоматической очисткой (например, удалять обработанные письма самим БП).
====

* *xref:Function_Monitiring_Messages.adoc[Мониторинг сообщений]* +
* *xref:Function_Message_Tasks5.adoc[Сообщения заданий 5]* +

*На уровень выше:* xref:FunctionDefinition.adoc[Описание функций бизнес-процессов]
