=  Свойства функций

Для каждой из указанных в бизнес-процессе функций определяется особый, присущий только ей набор свойств и параметров. Полное описание каждой функции производится в ее собственном диалоговом окне, открывающемся при выборе из ее контекстного меню пункта [.keyword .parmname]_Свойства_. Набор параметров, переменных и свойств для каждого типа функций различен, однако некоторое сходство все же присутствует:

* окна свойств всех функций содержат вкладку [.keyword]*Общие*, отличающиеся только пиктограммой функции;
* окна свойств всех функций содержат вкладку [.keyword]*Настройки вехи*; опции этой вкладки позволяют указать и контролировать допустимые сроки выполнения функции;
* окно свойств каждой функции в экземпляре бизнес-процесса содержит на одну вкладку больше, чем в шаблоне бизнес-процесса; эта вкладка называется [.keyword]*Экземпляры* и представляет собой описание участия функции в бизнес-процессе.

Некоторые функции (начальная, конечная, объединения «И» и «ИЛИ», а также разветвление) содержат только вкладки [.keyword]*Общие* и [.keyword]*Настройки вехи*, которых достаточно для их описания.

[NOTE]
====
[.note__title]#Прим.:# В последующих разделах вкладки [.keyword]*Основная*, [.keyword]*Настройки вехи* и [.keyword]*Экземпляры* настроек функций описываться не будут, поскольку являются идентичными для всех функций СУБП.
====

* *xref:Properties_Function_Tab_General.adoc[Общие свойства]* +
* *xref:Properties_Function_Tab_SettingsMilestone.adoc[Настройки вехи]* +
* *xref:Properties_Function_Tab_Instances.adoc[Вкладка 'Экземпляры' окна свойств функции]* +

*На уровень выше:* xref:BPbuilder_overview.adoc[Конструктор бизнес-процессов]
