= Исправленные ошибки

* DV5-6180 (SUP-4271). Исправлена ошибка, из-за которой бизнес процессы периодически останавливались с ошибкой: "Выполнение SQL операции было прервано из-за таймаута".
* DV5-6217 (SUP-4349). Возникала ошибка "DELETE нельзя использовать в не изменчивой (volatile) функции" в серверном расширении Workflow.
* DV5-6324 (SUP-4554). При обновлении модуля {pl} до версии 5.5.3 сбрасывалась учетная запись для сервиса StorageServer на значение по умолчанию.
* DV5-6404 (SUP-4679). В консоли настройки отсутствовал BackOffice SnapIn для шифрования учётных данных.
* DV5-6408 (SUP-4620). В карточке документа, открытой через задание, прокрутка не прокручивала до конца.
* DV5-6448 (SUP-4738). Исправлена ошибка, когда после обновления модуля {pl} до версии 5.5.3 инициатору согласования становилась недоступна кнопка Завершить этап если он не состоял в группе Администраторы КС.
* SUP-3498. Исправлена ошибка, вызывавшая большие (около 1000) очереди процессов на узлах кластера WF
* SUP-4146. Исправлена ошибка, при которой переставал отвечать БП "Экземпляр подпроцесса КС Подпроцесс работы с заданиями": ((0x0000) is an invalid culture identifier).